spring:
  application:
    name:  Spring Boot Basic Security
  datasource:
    url: jdbc:mysql://springsecurity.ct2gaqymmeqz.ap-southeast-1.rds.amazonaws.com/kennybank
    username: admin
    password: mysqladmin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: DEBUG