spring:
  application:
    name:  Spring Boot Basic Security
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: dbeaver
    password: dbeaver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security=${SPRING_SECURITY_LOG_LEVEL:TRACE}: # Set the log level for Spring Security