spring:
  application:
    name:  ${SPRING_APP_NAME:kennybankbackend}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USER:dbeaver}
    password: ${DATABASE_PASSWORD:dbeaver}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}

logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:TRACE}
        web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:TRACE}
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}